# ----------------------------------------------------------------------------
# FILE        : hugo.toml
# DESCRIPTION : Hugo configuration file
# AUTHOR      : Zoltán Király <public@zoltankiraly.com>
# CREATED     : 2024-08-26
# ----------------------------------------------------------------------------

# ----------------------------------------------------------------------------
# General configuration
# ----------------------------------------------------------------------------
title         = "Zoltan Kiraly"
baseURL       = "https://zoltankiraly.com"
languageCode  = "en-US"
theme         = "blush"

# ----------------------------------------------------------------------------
# Default site params
# ----------------------------------------------------------------------------
[params]
  author      = "Zoltan Kiraly"
  description = "Zoltan Kiraly"
  copyright   = "© {currentYear} Zoltan Kiraly"
  images      = ["site-social.jpg"]
  twittercard = true
  opengraph   = true

[params.logo]
  path        = ""
  alt         = "" # Falls back to site title if empty

# ----------------------------------------------------------------------------
# Posts
# ----------------------------------------------------------------------------
# Permalinks
[permalinks]
  posts = "posts/:year/:month/:slug"
  year  = "/posts/:slug/"
  month = "/posts/:slug/"

# Taxonomies
[taxonomies]
  year     = "year"
  month    = "month"
  tag      = "tags"
  category = "categories"