# ----------------------------------------------------------------------------
# FILE        : hugo.toml
# DESCRIPTION : Hugo configuration file
# AUTHOR      : Zoltán Király <public@zoltankiraly.com>
# CREATED     : 2024-08-26
# ----------------------------------------------------------------------------

# ----------------------------------------------------------------------------
# General configuration
# ----------------------------------------------------------------------------
title         = "Zoltan Kiraly"
baseURL       = "https://zoltankiraly.com"
languageCode  = "en-US"
theme         = "blush"

pygmentsUseClasses     = true

# Fall back to English if no translations are available
defaultContentLanguage = "en"

# Disabled languages
# e.g. ["hu", "es", "de"]
disableLanguages       = []

# ----------------------------------------------------------------------------
# Default site params
# ----------------------------------------------------------------------------
[params]
  author      = "Zoltan Kiraly"
  description = "Zoltan Kiraly"
  copyright   = "© {currentYear} Zoltan Kiraly"
  images      = ["site-social.jpg"]
  twittercard = true
  opengraph   = true

[params.logo]
  path        = ""
  alt         = "" # Falls back to site title if empty

# ----------------------------------------------------------------------------
# Languages
# ----------------------------------------------------------------------------
[languages]

  # English
  # --------------------------------------------------------------------------
  [languages.en]
    weight       = 1
    languageCode = "en-US"
    languageName = "English"

    # Menu
    [[languages.en.menu.main]]
      name   = "Home"
      url    = "/"
      weight = 1

    [[languages.en.menu.main]]
      name   = "About"
      url    = "/about/"
      weight = 2

    [[languages.en.menu.main]]
      name   = "Tags"
      url    = "/tags/"
      weight = 3

  # Hungarian
  # --------------------------------------------------------------------------
  # Override general configuration
  [languages.hu]
    weight       = 2
    languageCode = "hu"
    languageName = "Hungarian"

    # Menu
    [[languages.hu.menu.main]]
      name   = "Címlap"
      url    = "/"
      weight = 1

    [[languages.hu.menu.main]]
      name   = "Rólam"
      url    = "/about/"
      weight = 2

    [[languages.hu.menu.main]]
      name   = "Blog"
      url    = "/posts/"
      weight = 3

# ----------------------------------------------------------------------------
# Posts
# ----------------------------------------------------------------------------
# Permalinks
[permalinks]
  posts = "posts/:year/:month/:slug"
  year  = "/posts/:slug/"
  month = "/posts/:slug/"

# Taxonomies
[taxonomies]
  year     = "year"
  month    = "month"
  tag      = "tags"
  category = "categories"