---
title: "Installing Emacs from Source on FreeBSD"
date: 2024-08-03T04:10:00+02:00
author: Zoltan Kiraly
year: "2024"
month: "2024/08"
categories:
- Emacs
- FreeBSD
tags:
- emacs
- freebsd
keywords:
- emacs
draft: false
---

When it comes to installing Emacs on FreeBSD, you have a few options. The easiest method is to use the binary package with the following command:

#+begin_src sh
# pkg install emacs
#+end_src

Another option is to use the FreeBSD ports system:

#+begin_src sh
# cd /usr/ports/editors/emacs && make install clean
#+end_src

However, there might be times when you need to install Emacs from the official tar.xz source code. This could be because a new version is available that hasn't made it into the ports or binary packages yet, or because you want to compile Emacs with specific options to suit your needs. In this blog post, I will cover how to build Emacs from the official source code, giving you the flexibility to customize your installation exactly how you want it.

Please note that the instructions provided here were tested on FreeBSD 14.1-RELEASE running an Xorg environment.

Before making any changes, it's a good idea to take a snapshot of your system if you have FreeBSD installed on ZFS. This way, you can easily revert back if something goes wrong. To create a new snapshot, use the following command:

#+begin_src sh
# bectl create 2024-aug-04-before-installing-emacs
#+end_src

If you need to go back, simply select the snapshot in the FreeBSD boot menu, which is the first menu that shows up after you reboot your computer.

Install the following packages required for compiling Emacs:

#+begin_src sh
# pkg install autoconf gcc14-devel gmake texinfo
#+end_src

Download the Emacs source and extract it:

#+begin_src sh
$ wget http://mirrors.nav.ro/gnu/emacs/emacs-29.4.tar.xz
$ tar xvf emacs-29.4.tar.xz
#+end_src

Now, go into the directory where the tar.xz file was extracted and start by running:

#+begin_src sh
$ ./autogen_sh
#+end_src

If this completes without any errors, proceed with:

#+begin_src sh
$ ./configure --prefix="$HOME/.local/emacs/" --without-compress-install --with-native-compilation --with-json --with-mailutils --with-tree-sitter CC=gcc14 ac_cv_header_sys_sysinfo_h=no
#+end_src

This will configure Emacs to be installed with native compilation support and other specified features.



Blog post work in progress.