---
title: "Installing Emacs from Source on FreeBSD"
date: 2024-08-03T04:10:00+02:00
author: Zoltan Kiraly
year: "2024"
month: "2024/08"
categories:
- Emacs
- FreeBSD
tags:
- emacs
- freebsd
keywords:
- emacs
draft: false
---

When it comes to installing Emacs on FreeBSD, you have a few options. The easiest method is to use the binary package with the following command:

#+begin_src sh
# pkg install emacs
#+end_src

Another option is to use the FreeBSD ports system:

#+begin_src sh
cd /usr/ports/editors/emacs && make install clean
#+end_src

However, there might be times when you need to install Emacs from the official tar.xz source code. This could be because a new version is available that hasn't made it into the ports or binary packages yet, or because you want to compile Emacs with specific options to suit your needs. In this blog post, I will cover how to build Emacs from the official source code, giving you the flexibility to customize your installation exactly how you want it.

Please note that the instructions provided here were tested on FreeBSD 14.1-RELEASE running an Xorg environment.

Blog post work in progress.